name: JSON Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jsonlint
      run: |
        npm install -g jsonlint

    - name: List files
      run: |
        ls -lash


    - name: Run jsonlint
      run: |
        find json -name "*.json" -exec jsonlint --quiet {} \;
        echo $?
        if [ $? -ne 0 ]; then
          echo "JSON linting failed"
          exit 1
        fi
