name: JSON Linting

on:
  push:
    branches:
      - digital
  pull_request:
    branches:
      - digital

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jsonlint
      run: |
        npm install -g jsonlint-cli

    - name: List files
      run: |
        ls -lash


    - name: Run jsonlint
      run: |
        jsonlint-cli json/*.json
